name: Test coverage

on:
  pull_request:
    branches: [ "master" ]

jobs:
  job1:
    name: Test coverage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Run jacoco on all modules
        run: ./gradlew debugCoverage

      - name: Combine jacoco reports
        run: ./gradlew allDebugCoverage

      - name: Upload report
        uses: actions/upload-artifact@v3
        with:
          name: report
          path: build/reports/jacoco/allDebugCoverage

      - name: Download test reports
        uses: actions/download-artifact@v3
        with:
          name: report
          path: build/reports/jacoco/allDebugCoverage

      - name: Upload to codecov
        uses: codecov/codecov-action@v3
        with:
          files: "build/reports/jacoco/allDebugCoverage/allDebugCoverage.xml"

      - name: Add coverage to PR
        id: jacoco
        uses: madrapps/jacoco-report@v1.3
        with:
          paths: ${{ github.workspace }}/build/reports/jacoco/allDebugCoverage/allDebugCoverage.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 5
          min-coverage-changed-files: 0 # temporary
