name: Build and run tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  job1:
    name: Build project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v1

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run unit tests
        run: bash ./gradlew test --stacktrace

  job2:
    needs: job1
    name: Test coverage
    runs-on: ubuntu-latest

    steps:
      - name: Run jacoco
        run: ./gradlew testDebugUnitTest

      - name: Generate report
        uses: actions/upload-artifact@v2
        with:
          name: report
          path: app/build/reports/coverage/debug

      - name: Download report
        uses: actions/download-artifact@v2
        with:
          name: report
          path: app/build/reports/coverage/debug

      - name: Upload report
        uses: codecov/codecov-action@v2
        with:
          files: "app/build/reports/coverage/debug/report.xml"
